const PRFX = '@auth/';

export const FETCH_LOGIN_BY_GOOGLE = `${PRFX}FETCH_LOGIN_BY_GOOGLE`;
export const SAVE_LOGIN_BY_GOOGLE = `${PRFX}SAVE_LOGIN_BY_GOOGLE`;
export const FAIL_LOGIN_BY_GOOGLE = `${PRFX}FAIL_LOGIN_BY_GOOGLE`;

export const LOGOUT_REQUEST = `${PRFX}LOGOUT_REQUEST`;

export const CLEAR_AUTH = `${PRFX}CLEAR_AUTH`;