const PRFX = '@contacts/';

export const FETCH_CONTACTS = `${PRFX}FETCH_CONTACTS`;
export const SAVE_CONTACTS = `${PRFX}SAVE_CONTACTS`;

export const CHANGE_FILTERS_CONTACTS = `${PRFX}CHANGE_FILTERS_CONTACTS`;
export const SAVE_FILTERS_CONTACTS = `${PRFX}SAVE_FILTERS_CONTACTS`;